export const ButtonStyle = {
  variants: {
    navButton: {
      fontSize: "25px",
      color: "white",
      bg: "transparent",
      h: "100%",
      border: "0",
      borderRadius: "0",
      m: "0",
      px: "4",
      py: "2",
      fontFamily: "anton",
      fontWeight: "200",
    },
    blogButton: {
      fontSize: "25px",
      color: "white",
      bg: "mainOrange",
      h: "100%",
      border: "0",
      borderRadius: "0",
      m: "0",
      px: "4",
      py: "2",
      fontFamily: "anton",
      fontWeight: "200",
    },
    responsiveNavButton: {
      fontSize: "25px",
      color: "black",
      bg: "transparent",
      h: "100px",
      w: "100%",
      fontFamily: "anton",
      fontWeight: "light",
    },
    whytrekkingButton: {
      background: "#FF3606",
      borderRadius: "10px",
      width: "170px",
      height: "30px",
      fontSize: ["10px", "12px", "18px", "18px"],
      color: "#FFFFFF",
      padding: "0px 0px",
      fontFamily: "anton",
      fontWeight: "100",
    },
    footerButton: {
      background: "#FF3606",
      width: ["100px", "130px", "180px", "210px"],
      height: ["38px", "45px", "55px", "60px"],
      fontWeight: "100",
      fontSize: ["17px", "21px", "25px", "30px"],
      color: "#FFFFFF",
      borderRadius: ["50px", "50px", "0px", "0px"],
      margin: "auto",
      fontFamily: "anton",
    },
  },
};
