export const ButtonStyle = {
  variants: {
    navButton: {
      h: "38px",
      fontSize: "20px",
      color: "#111111;",
      bg: "transparent",
      border: "0",
      borderRadius: "0",
      m: "0",
      py: "0",
      px: "4",
      fontFamily: "Roboto",
      fontWeight: "700",
      fontStyle: "normal",
      _hover: {
        color: "white",
      },
    },
    blogButton: {
      h: "43px",
      width: "142px",
      fontSize: "20px",
      color: "#FF461D",
      bg: "#111111",
      border: "0",
      borderRadius: "100px",
      _hover: {
        color: "white",
      },

      py: "10px",
      px: "20px",
      fontFamily: "Roboto",
      fontWeight: "700",
    },
    responsiveNavButton: {
      fontSize: "25px",
      color: "black",
      bg: "transparent",
      h: "100px",
      w: "100%",
      fontFamily: "anton",
      fontWeight: "light",
      letterSpacing: "3px",
      textTransform: "uppercase",
    },
    whytrekkingButton: {
      background: "#FF3606",
      borderRadius: "10px",
      width: "170px",
      height: "30px",
      fontSize: ["10px", "12px", "18px", "18px"],
      color: "#FFFFFF",
      padding: "0px 0px",
      fontFamily: "anton",
      fontWeight: "100",
    },
    footerButton: {
      background: "#FF3606",
      width: ["100px", "130px", "180px", "210px"],
      height: ["38px", "45px", "50px", "50px"],
      fontWeight: "100",
      fontSize: ["17px", "21px", "25px", "30px"],
      color: "#FFFFFF",
      borderRadius: ["50px", "50px", "0px", "0px"],
      margin: "auto",
      fontFamily: "anton",
    },
    calendar_btn: {
      background: "white",
      borderRadius: "20px",
      fontSize: "14px",
      color: "black",
      py: "1",
      px: "3",
      m: "1",
      h: "100%",
    },
    serviceButton: {
      padding: "10px 30px",
      width: "183px",
      height: "40px",
      background: "#FF461D",
      borderRadius: "60px",
      color: "white",
    },
  },
};
