import Gallery from "../components/Gallery";

export const TextStyle = {
  variants: {
    // ***********************about page***********
    aboutHeader: {
      as: "h3",
      fontWeight: "400",
      fontSize: "23px",
      color: "#000000",
      fontFamily: "anton",
      fontWeight: "400",
    },
    aboutbutton: {
      as: "a",
      color: "#FF3606",
      fontWeight: "400",
      fontSize: "23px",
      fontFamily: "sen",
      cursor: "pointer",
    },
    aboutParagraph: {
      as: "h4",
      fontSize: "15p",
      fontWeight: "400",
      fontFamily: "sans-serif",
      textAlign: "center",
    },

    // **********************Home page*****************

    homeHeader1: {
      as: "p",
      color: " black",
      fontSize: ["45px", "50px", "70px", "80px"],
      fontFamily: "anton",
      p: "0",
      m: "0",
      position: "relative",
      bottom: ["-20px", "-20px", "-40px", "-40px"],
      textAlign: "center",
    },
    homeHeader2: {
      as: "p",
      color: "#FF4417",
      fontSize: ["55px", "60px", "120px", "140px"],
      fontWeight: "400",
      fontFamily: "Rubik Glitch",
      p: "0",
      m: "0",
    },

    // ************************destination page****************

    destinationHeader: {
      as: "h1",
      fontWeight: "400",
      fontSize: ["58px", "58px", "80px", "80px"],
      color: "#00000",
      opacity: "0.5",
      p: ["0", "30", "0", "0"],
      m: "0",
      textTransform: "uppercase",
      fontFamily: "anton",
      letterSpacing: ["8px", "8px", "5px", "5px"],
    },

    destinationHeading1: {
      as: "h3",
      position: "absolute",
      fontFamily: "anton",
      fontSize: ["15px", "15px", "20px", "20px"],
      fontWeight: "300",
      color: "#FFFFFF",
      // textAlign:"center"
      pl: "1",
      m: "0",
      // p:{["31", "31", "0", "0"]}
      letterSpacing: ["2px", "2px", "3px", "3px"],
    },
    destinationHeading2: {
      as: "h2",
      fontSize: ["18px", "20px", "22px", "24px"],
      fontWeight: "400",
      color: "#3E3E3E",
      textAlign: ["center", "center", "center", "start"],
      fontFamily: "anton",
    },
    destinationHeading3: {
      fontSize: ["18px", "18px", "25px", "25px"],
      fontWeight: "400",
      textAlign: "center",
      color: "#3E3E3E",
      p: "40px",
      pt: "20px",
      fontFamily: "anton",
    },
    destinationPerson: {
      as: "h1",
      color: "#FFFFFF",
      fontWeight: "400",
      fontSize: ["10px", "12px", "15px", "15px"],
      fontFamily: "anton",
    },
    destinationDays: {
      as: "h1",
      color: "#FFFFFF",
      fontWeight: "400",
      fontSize: ["10px", "12px", "15px", "15px"],
      fontFamily: "anton",
    },
    destinationPerperson: {
      as: "h1",
      fontWeight: "400",
      fontSize: ["10px", "12px", "15px", "15px"],
      color: "#FF4417",
      fontFamily: "anton",
    },
    destinationStartexploring: {
      fontWeight: "200",
      fontSize: "20px",
      color: "#FF3606",
      textAlign: "center",
      fontFamily: "anton",
      // mb: "5",
      // mt: "1",
      // position:"absolute"
    },
    //  *************************************service page*************
    serviceHeader: {
      as: "h1",
      fontSize: ["20px", "25px", "33px", "33px"],
      fontWeight: "400",
      fontFamily: "anton",
      letterSpacing: ["8px", "8px", "5px", "5px"],
    },

    serviceHeader1: {
      as: "p",
      fontWeight: "400",
      fontSize: ["50px", "60px", "110px", "124px"],
      letterSpacing: "0.04em",
      color: "#000000",
      opacity: "0.19",
      padding: "0px 20px",
      fontFamily: "anton",
      // letterSpacing: ["8px", "8px", "5px", "5px"],
    },
    serviceHeader2: {
      as: "p",
      fontWeight: "400",
      fontSize: ["10px", "15px", "20px", "30px"],
      letterSpacing: "0.04em",
      color: "#FF3606",
      position: "absolute",
      textAlign: "center",
      fontFamily: "anton",
    },
    serviceParagraph: {
      as: "p",
      fontSize: ["12px", "12px", "15px", "18px"],
      fontWeight: "400",
      color: "#8B8B8B",
      fontFamily: "anton",
      letterSpacing: "0.02em",
      // p:"10px 0px 20px 0px"
    },

    // ********************Why trekking with us******************

    whytrekkingHeader1: {
      as: "h1",
      fontWeight: "400",
      fontSize: ["32px", "32px", "47px", "70px"],
      color: "#FFFFFF",
      opacity: "0.39",
      m: "0",
      textAlign: ["center", "center", "start", "start"],
      textTransform: "uppercase",
      fontFamily: "anton",
      letterSpacing: ["8px", "8px", "5px", "5px"],
      lineHeight: "2",
    },
    whytrekkingHeader2: {
      as: "h3",
      position: "absolute",
      fontSize: ["12px", "12px", "18px", "20px"],
      fontWeight: "400",
      color: "#FFFFFF",
      fontFamily: "anton",
      p: "1px  0px 1px 1px",
      letterSpacing: "2",
    },
    whytrekkingHeading: {
      color: "#FFFFFF",
      fontSize: ["10px", "20px", "30px", "30px"],
      fontWeight: "400",
      textAlign: "center",
      fontFamily: "anton",
    },

    // ********************************Gallery page(Journey)**********
    galleryHeader1: {
      as: "h1",
      fontWeight: "400",
      fontSize: ["55px", "60px", "80px", "80px"],
      color: "#000000",
      opacity: "0.19",
      padding: "0px 20px",
      fontFamily: "anton",
      letterSpacing: ["20px", "20px", "8px", "8px"],
    },

    galleryHeader2: {
      as: "h3",
      fontWeight: "400",
      fontSize: ["18px", "18px", "20px", "22px"],
      wordSpacing: "0.54em",
      color: "black",
      position: "absolute",
      textAlign: "center",
      fontFamily: "anton",
      letterSpacing: "2px",
    },

    // ********************************Testimonal page**********

    testimonalHeader: {
      fontWeight: "400",
      fontSize: "25px",
      letterpSacing: "0.02em",
      color: "#ffffff",
      fontFamily: "anton",
      letterSpacing: ["8px", "8px", "5px", "5px"],
    },

    testimonalHeader1: {
      as: "h1",
      fontWeight: "400",
      fontSize: ["43px", "60px", "80px", "80px"],
      color: "#000000",
      opacity: "0.19",
      fontFamily: "anton",
      letterSpacing: ["8px", "8px", "5px", "5px"],
    },
    testimonalHeader2: {
      as: "p",
      fontWeight: "400",
      fontSize: ["12px", "15px", "25px", "25px"],
      color: "#FF3606",
      position: "absolute",
      textAlign: "center",
      fontFamily: "anton",
    },
    testimonalParagraph: {
      as: "p",
      color: " #FFFFFF",
      fontSize: ["15px", "15px", "20px", "20px"],
      textAlign: ["center", "center", "start", "start"],
      fontFamily: "anton",
      fontWeight: "200",
      letterSpacing: "2",
    },
    testimonalHeading: {
      fontWeight: "400",
      fontSize: ["12px", "15px", "20px", "23px"],
      letterSpacing: "0.01em",
      color: "#ffffff",
      fontFamily: "anton",
      fontWeight: "300",
    },

    testimonalHeading1: {
      as: "p",
      color: " black",
      fontSize: ["25px", "25px", "35px", "35px"],
      textAlign: ["center", "center", "start", "start"],
      fontFamily: "anton",
      fontWeight: "light",
    },
    testimonalHeading2: {
      as: "p",
      color: " #FFFFFF",
      fontSize: ["15px", "15px", "23px", "23px"],
      textAlign: ["center", "center", "start", "start"],
      fontFamily: "anton",
    },

    // ******************************blog page************
    blogHeader: {
      fontWeight: "300",
      fontSize: ["15px", "20px", "30px", "30px"],
      letterSpacing: "0.02em",
      color: "#000000",
      fontFamily: "anton",
      mt: "2",
      textAlign: "center",
    },
    blogDate: {
      fontWeight: "400",
      fontSize: ["12px", "12px", "14px", "14px"],
      letterSpacing: "0.02em",
      color: "red",
      fontFamily: "kanit",
      textAlign: "center",
      w: "auto",
      my: "2",
      px: "3",
      bg: "white",
      borderRadius: "20px",
    },
    blogDescription: {
      fontWeight: "300",
      fontSize: ["13px", "13px", "15px", "15px"],
      letterSpacing: "0.02em",
      color: "white",
      fontFamily: "kanit",
      h: "100%",
      overflow: "hidden",
      textOverflow: "ellipsis",
    },
    blogParagraph: {
      fontWeight: "300",
      fontSize: ["14px", "14px", "18px", "18px"],
      letterSpacing: "0.02em",
      color: "white",
      fontFamily: "kanit",
    },
    blogReadmore: {
      fontWeight: "400",
      fontSize: ["10px", "10px", "15px", "15px"],
      letterSpacing: "0.02em",
      color: "#000000",
      fontFamily: "anton",
      textAlign: "right",
      w: "100%",
      mt: "3",
    },
    blogMainheader: {
      as: "h1",
      fontWeight: "400",
      fontSize: ["46px", "60px", "90px", "100px"],
      letterSpacing: "0.04em",
      color: "white",
      opacity: "0.5",
      padding: "0px 20px",
      fontFamily: "anton",
    },
    blogMainheader1: {
      as: "h3",
      fontWeight: "400",
      fontSize: ["10px", "15px", "20px", "30px"],
      letterSpacing: "0.04em",
      color: "black",
      position: "absolute",
      textAlign: "center",
      fontFamily: "anton",
    },

    calendarModalText: {
      fontWeight: "bold",
      mt: "2",
    },

    secretLocationHeader: {
      fontFamily: "Anton",
      fontStyle: "normal",
      fontWeight: "400",
      fontSize: ["30px", "35px", "40px", "45px"],
      lineHeight: ["50px", "70px"],
      letterSpacing: "0.04em",
      color: "#000000",
    },
    secretLocationText: {
      // fontFamily: "Anton",
      // fontStyle: "normal",
      // fontWeight: "light",
      fontSize: ["14px", "14px", "14px", "16px"],
      lineHeight: "16px",
      wordSpacing: "0.14em",
      color: "#000000d1",
      mt: "10%",
    },
    secretLocationNumber: {
      fontFamily: "Anton",
      fontStyle: "normal",
      fontWeight: "400",
      fontSize: ["50px", "50px", "100px", "100px"],
      lineHeight: ["101px", "151px"],
      letterSpacing: "0.04em",
      color: "rgba(0, 0, 0, 0.5)",
      px: "4",
    },

    // ******************************footer page************
    footerQuicklink: {
      as: "h1",
      color: "#FF3606",
      fontWeight: "400",
      fontSize: ["13px", "22px", "27px", "30px"],
      pb: "15px",
      fontFamily: "anton",
    },
    footerQuicklinks: {
      as: "h3",
      color: "#FFFFFF",
      fontSize: ["14px", "17px", "23px", "23px"],
      fontFamily: "anton",
      fontWeight: "100",
      display: "flex",
      cursor: "pointer",
    },
    footerQuicklinksSpan: {
      color: "red",
      fontSize: ["13px", "17px", "23px", "23px"],
      fontFamily: "anton",
      pr: "1",
    },
  },
};
