import Gallery from "../components/Gallery";

export const TextStyle = {
  variants: {
    // ***********************about page***********
    aboutHeader: {
      as: "h3",
      fontWeight: "500",
      color: "#FFFFFF",
      fontFamily: "Roboto",
      fontWeight: "400",
    },
    aboutbutton: {
      as: "a",
      color: "#591433",
      fontWeight: "500",
      fontSize: "16px",
      fontFamily: "Roboto",
      cursor: "pointer",
    },
    aboutParagraph: {
      as: "h4",
      fontWeight: "400",
      fontFamily: "Roboto",
      textAlign: "center",
      color: "#FFFFFF",
    },

    // **********************Home page*****************

    homeHeader1: {
      as: "p",
      color: " #591433",
      fontSize: ["45px", "50px", "70px", "84px"],
      fontFamily: "anton",
      p: "0",
      m: "0",
      position: "relative",
      bottom: ["-20px", "-20px", "-40px", "-40px"],
      textAlign: "center",
      fontWeight: "400",
    },
    homeHeader2: {
      as: "p",
      color: "rgba(255, 255, 255, 0.60)",
      fontSize: ["55px", "60px", "108px", "108px"],
      fontWeight: "400",
      fontFamily: "Rubik Glitch",
      p: "0",
      m: "0",
      
    },

    // ************************destination page****************

    destinationHeader: {
      as: "h1",
      fontWeight: "400",
      fontSize: ["35px", "35px", "70px", "70px"],
      color: "rgba(255, 255, 255, 0.6)",
      lineHeight: ["41px", "41px", "82px", "82px"],
      textTransform: "uppercase",
      fontFamily: "Rubik Glitch",
      letterSpacing: ["8px", "8px", "5px", "5px"],
    },

    destinationHeading1: {
      as: "h3",
      fontFamily: "anton",
      fontSize: ["15px", "15px", "20px", "20px"],
      fontWeight: "300",
      color: "#FF461D",
      lineHeight: "24px",
      letterSpacing: ["2px", "2px", "3px", "3px"],
    },
    destinationHeading2: {
      as: "p",
      fontSize: ["16px", " 16px", "22x", "22px"],
      fontWeight: "400",
      color: "#3E3E3E",
      textAlign: ["center", "center", "center", "start"],
    },
    destinationHeading3: {
      fontSize: ["18px", "18px", "25px", "25px"],
      fontWeight: "400",
      textAlign: "center",
      color: "#3E3E3E",
      p: "40px",
      pt: "20px",
      fontFamily: "anton",
    },
    destinationSecondaryText: {
      as: "h1",
      color: "#FFFFFF",
      fontWeight: "400",
      fontSize: ["10px", "12px", "15px", "15px"],
      fontFamily: "anton",
      letterSpacing: "1px",
    },
    destinationSecondaryText2: {
      as: "h1",
      color: "mainOrange",
      fontWeight: "400",
      fontSize: ["10px", "12px", "15px", "15px"],
      fontFamily: "anton",
      letterSpacing: ".5px",
    },

    destinationStartexploring: {
      fontWeight: "200",
      fontSize: "20px",
      color: "#FF3606",
      textAlign: "center",
      fontFamily: "anton",
      // color: "#ffffffe3",
      letterSpacing: "1px",
      // mb: "5",
      // mt: "1",
      // position:"absolute"
    },
    //  *************************************service page*************
    serviceHeader: {
      as: "h1",
      fontSize: ["35px", "35px", "70px", "70px"],
      fontWeight: "400",
      fontFamily: "Rubik Glitch",
      color: "rgba(33, 0, 17, 0.8)",
      letterSpacing: ["8px", "8px", "5px", "5px"],
      lineHeight: ["24px", "24px", "83px", "83px"],
    },

    serviceHeader1: {
      as: "p",
      fontWeight: "400",
      fontSize: ["16px", "16px", "23px", "23px"],
      letterSpacing: "0.04em",
      color: "#FF461D",
      padding: "0px 20px",
      fontFamily: "anton",
      lineHeight: "35px",
      // letterSpacing: ["8px", "8px", "5px", "5px"],
    },
    serviceHeader2: {
      as: "p",
      fontWeight: "500",
      fontSize: ["17px", "17px", "20px", "20px"],
      color: "#FFFFFF",
      textAlign: "center",
      fontFamily: "Roboto",
      lineHeight: "23px",
    },
    serviceParagraph: {
      as: "p",
      fontSize: ["12px", "12px", "12px", "12px"],
      fontWeight: "400",
      color: "#FFFFFF",
      fontFamily: "Roboto",
      textAlign: "center",
      lineHeight: "19px",
    },

    // ********************Why trekking with us******************

    whytrekkingHeader1: {
      as: "h1",
      fontWeight: "400",
      fontSize: ["35px", "35px", "47px", "70px"],
      color: "rgba(255, 255, 255, 0.6)",
      opacity: "0.39",
      m: "0",
      textAlign: ["center", "center", "start", "start"],
      textTransform: "uppercase",
      fontFamily: "Rubik Glitch",
      lineHeight: "45px",
    },
    whytrekkingHeader2: {
      as: "h3",
      // position: "absolute",
      fontSize: ["16px", "16px", "18px", "20px"],
      fontWeight: "400",
      color: "#FF461D",
      fontFamily: "anton",
      lineHeight: "24PX",
      letterSpacing: "2",
    },
    whytrekkingHeading: {
      color: "#FFFFFF",
      fontSize: ["10px", "20px", "30px", "30px"],
      fontWeight: "400",
      textAlign: "center",
      fontFamily: "anton",
    },

    // ********************************Gallery page(Journey)**********
    galleryHeader1: {
      as: "h1",
      fontWeight: "400",
      fontSize: ["55px", "60px", "80px", "80px"],
      color: "#000000",
      opacity: "0.19",
      padding: "0px 20px",
      fontFamily: "anton",
      letterSpacing: ["20px", "20px", "8px", "8px"],
    },

    galleryHeader2: {
      as: "h3",
      fontWeight: "400",
      fontSize: ["18px", "18px", "20px", "22px"],
      wordSpacing: "0.54em",
      color: "black",
      position: "absolute",
      textAlign: "center",
      fontFamily: "anton",
      letterSpacing: "2px",
    },

    // ********************************Testimonal page**********

    testimonalHeader: {
      fontWeight: "400",
      fontSize: "25px",
      letterpSacing: "0.02em",
      color: "#ffffff",
      fontFamily: "anton",
      letterSpacing: ["8px", "8px", "5px", "5px"],
    },

    testimonalHeader1: {
      as: "h1",
      fontWeight: "400",
      fontSize: ["35px", "35px", "70px", "70px"],
      color: "#000000",
      opacity: "0.19",
      fontFamily: "anton",
      letterSpacing: ["8px", "8px", "5px", "5px"],
    },
    testimonalHeader2: {
      as: "p",
      fontWeight: "400",
      fontSize: ["16px", "16px", "25px", "25px"],
      color: "#FF3606",
      position: "absolute",
      textAlign: "center",
      fontFamily: "anton",
    },
    testimonalParagraph: {
      as: "p",
      color: " #FFFFFF",
      fontSize: ["15px", "15px", "20px", "20px"],
      textAlign: ["center", "center", "start", "start"],
      fontFamily: "anton",
      fontWeight: "200",
      letterSpacing: "2",
    },
    testimonalHeading: {
      fontWeight: "400",
      fontSize: ["12px", "15px", "20px", "23px"],
      letterSpacing: "0.01em",
      color: "#ffffff",
      fontFamily: "anton",
      fontWeight: "300",
    },

    testimonalHeading1: {
      as: "p",
      color: " black",
      fontSize: ["25px", "25px", "35px", "35px"],
      textAlign: ["center", "center", "start", "start"],
      fontFamily: "anton",
      fontWeight: "light",
    },
    testimonalHeading2: {
      as: "p",
      color: " #FFFFFF",
      fontSize: ["15px", "15px", "23px", "23px"],
      textAlign: ["center", "center", "start", "start"],
      fontFamily: "anton",
    },

    // ******************************blog page************
    blogHeader: {
      fontWeight: "300",
      fontSize: ["15px", "20px", "30px", "30px"],
      letterSpacing: "0.02em",
      color: "#000000",
      fontFamily: "anton",
      mt: "2",
      textAlign: "center",
    },
    blogDate: {
      fontWeight: "400",
      fontSize: ["12px", "12px", "14px", "14px"],
      letterSpacing: "0.02em",
      color: "red",
      fontFamily: "kanit",
      textAlign: "center",
      w: "auto",
      my: "2",
      px: "3",
      bg: "white",
      borderRadius: "20px",
    },
    blogDescription: {
      fontWeight: "300",
      fontSize: ["13px", "13px", "15px", "15px"],
      letterSpacing: "0.02em",
      color: "white",
      fontFamily: "kanit",
      h: "100%",
      overflow: "hidden",
      textOverflow: "ellipsis",
    },
    blogParagraph: {
      fontWeight: "300",
      fontSize: ["14px", "14px", "18px", "18px"],
      letterSpacing: "0.02em",
      color: "white",
      fontFamily: "kanit",
    },
    blogReadmore: {
      fontWeight: "400",
      fontSize: ["10px", "10px", "15px", "15px"],
      letterSpacing: "0.02em",
      color: "#000000",
      fontFamily: "anton",
      textAlign: "right",
      w: "100%",
      mt: "3",
    },
    blogMainheader: {
      as: "h1",
      fontWeight: "400",
      fontSize: ["46px", "60px", "90px", "100px"],
      letterSpacing: "0.04em",
      color: "white",
      opacity: "0.5",
      padding: "0px 20px",
      fontFamily: "anton",
    },
    blogMainheader1: {
      as: "h3",
      fontWeight: "400",
      fontSize: ["10px", "15px", "20px", "30px"],
      letterSpacing: "0.04em",
      color: "black",
      position: "absolute",
      textAlign: "center",
      fontFamily: "anton",
    },

    calendarModalText: {
      fontWeight: "bold",
      mt: "2",
    },

    secretLocationHeader: {
      fontFamily: "Anton",
      fontStyle: "normal",
      fontWeight: "400",
      fontSize: ["30px", "35px", "40px", "45px"],
      lineHeight: ["50px", "70px"],
      letterSpacing: "0.04em",
      color: "#000000",
    },
    secretLocationText: {
      fontFamily: "Kanit",
      // fontStyle: "normal",
      // fontWeight: "light",
      fontSize: ["14px", "14px", "18px", "18px"],
      lineHeight: "22px",
      wordSpacing: "0.14em",
      color: "#000000d1",
      mt: "10%",
    },
    secretLocationNumber: {
      fontFamily: "Anton",
      fontStyle: "normal",
      fontWeight: "400",
      fontSize: ["50px", "50px", "100px", "100px"],
      lineHeight: ["101px", "151px"],
      letterSpacing: "0.04em",
      color: "rgba(0, 0, 0, 0.5)",
      px: "4",
    },

    // ******************************footer page************
    footerQuicklink: {
      as: "h1",
      color: "#FF3606",
      fontWeight: "400",
      fontSize: ["13px", "22px", "27px", "30px"],
      pb: "15px",
      fontFamily: "anton",
    },
    footerQuicklinks: {
      as: "h3",
      color: "#FFFFFF",
      fontSize: ["14px", "17px", "23px", "23px"],
      fontFamily: "anton",
      fontWeight: "100",
      display: "flex",
      cursor: "pointer",
    },
    footerQuicklinksSpan: {
      color: "red",
      fontSize: ["13px", "17px", "23px", "23px"],
      fontFamily: "anton",
      pr: "1",
    },
  },
};
